### ISSUE TITLE
Question about CORS

### ISSUE THREAD

**Issue by CalvinChang-tw** [markstarkart/serverless-todo#13]
Hi, I am building TODO LIST from lambda + S3 as static website hosting as well.
My 'POST' and 'DELETE' requests are all blocked due to CORS,
But My 'GET' requests works.

Do you know how to fix it?
Or how do you overcome CORS problem,
in the end, the lambda api url is not the same as S3 bucket hosting

```

    async addTodo(name) {
        let response = await fetch(`${LAMBDA_HOST}`, {
            method: 'post',
            data: {
                name
            },
            headers: {
                Accept: 'application/json',
                'Content-Type': 'application/json'
            }
        }).then((res) => res.json());
        this.setState({
            todoList: [...this.state.todoList, response]
        });
    }
```

**Comment by uuidforme** [comment]
Hey Calvin,

CORS can be a real pain. I have a CORS policy on my S3 bucket that is very open. If you look at my handlers I have CORS headers in my responses. In my template.yaml, I added a CORS property to API globals.

**Comment by CalvinChang-tw** [comment]
Many thanks! I thought I was unable to configure the API Gateway!
